In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('Housing.csv')
data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [4]:
data.isna().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [5]:
data.duplicated().sum()

0

In [6]:
numdata = data.select_dtypes(include='number')
otherdata = data.select_dtypes(include='object')
numdata.head(),otherdata.head()

(      price  area  bedrooms  bathrooms  stories  parking
 0  13300000  7420         4          2        3        2
 1  12250000  8960         4          4        4        3
 2  12250000  9960         3          2        2        2
 3  12215000  7500         4          2        2        3
 4  11410000  7420         4          1        2        2,
   mainroad guestroom basement hotwaterheating airconditioning prefarea  \
 0      yes        no       no              no             yes      yes
 1      yes        no       no              no             yes       no
 2      yes        no      yes              no              no      yes
 3      yes        no      yes              no             yes      yes
 4      yes       yes      yes              no             yes       no

   furnishingstatus
 0        furnished
 1        furnished
 2   semi-furnished
 3        furnished
 4        furnished  )

In [7]:
x = numdata.drop('price',axis=1)
y = data['price']
x.head()

   area  bedrooms  bathrooms  stories  parking
0  7420         4          2        3        2
1  8960         4          4        4        3
2  9960         3          2        2        2
3  7500         4          2        2        3
4  7420         4          1        2        2

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.30,random_state=42)
print("X train:", X_train.shape)
print("X test:", X_test.shape)
print("Y train:", Y_train.shape)
print("Y test:", Y_test.shape)

X train: (381, 5)
X test: (164, 5)
Y train: (381,)
Y test: (164,)

In [9]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train,Y_train)

LinearRegression()

In [10]:
lr.score(X_train,Y_train)

0.5797092579395215

In [15]:
y_train_pred = lr.predict(X_train)
y_test_pred = lr.predict(X_test)

In [16]:
res = pd.DataFrame({
    "Actual": Y_test.values,
    "Predicted": y_test_pred
})
res.head(10)

    Actual     Predicted
0  4060000  6.298756e+06
1  6650000  6.412300e+06
2  3710000  3.301998e+06
3  6440000  4.251721e+06
4  2800000  3.436733e+06
5  4900000  4.345562e+06
6  5250000  5.729237e+06
7  4543000  5.603626e+06
8  2450000  3.434050e+06
9  3353000  3.021832e+06

In [28]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
tmae = mean_absolute_error(Y_train, y_train_pred)
tmse = mean_squared_error(Y_train, y_train_pred)
trmse = tmse ** 0.5 
tr2 = r2_score(Y_train, y_train_pred)

print("Train Data Set performance")
print("Mean Absolute Error :", tmae)
print("Mean Squared Error  :", tmse)
print("TRMSE:", trmse)
print("R2  :", tr2)

Train Data Set performance
Mean Absolute Error : 851921.2094211405
Mean Squared Error  : 1320370733904.5688
TRMSE: 1149073.8592033884
R2  : 0.5797092579395215

In [29]:
tmae = mean_absolute_error(Y_test, y_test_pred)
tmse = mean_squared_error(Y_test, y_test_pred)
trmse = tmse ** 0.5
tr2 = r2_score(Y_test,y_test_pred)

print("test Data Set ")
print("Mean Absi=olute Error :", tmae)
print("Mean Squatrd Error :", tmse)
print("TRMSE:", trmse)
print("R2  :", tr2)

test Data Set
Mean Absi=olute Error : 1065137.8263727794
Mean Squatrd Error : 2044165115591.7861
TRMSE: 1429743.0243200301
R2  : 0.5253182966980272

In [26]:
lr.coef_

array([3.29285878e+02, 1.61077479e+05, 1.19412059e+06, 4.72530548e+05,
       3.95480372e+05])

In [27]:
lr.intercept_

-17122.995142479427

## Done Prediction of Housing DataSet