In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('student_habits_performance.csv')
data.head()

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4

In [3]:
data.isna().sum()

student_id                       0
age                              0
gender                           0
study_hours_per_day              0
social_media_hours               0
netflix_hours                    0
part_time_job                    0
attendance_percentage            0
sleep_hours                      0
diet_quality                     0
exercise_frequency               0
parental_education_level         0
internet_quality                 0
mental_health_rating             0
extracurricular_participation    0
exam_score                       0
dtype: int64

In [4]:
data.duplicated().sum()

0

In [5]:
numdata = data.select_dtypes(include='number')
otherdata = data.select_dtypes(include='object')

In [6]:
numdata
otherdata

,student_id,gender,part_time_job,diet_quality,parental_education_level,internet_quality,extracurricular_participation
0,S1000,Female,No,Fair,Master,Average,Yes
1,S1001,Female,No,Good,High School,Average,No
2,S1002,Male,No,Poor,High School,Poor,No
3,S1003,Female,No,Poor,Master,Good,Yes
4,S1004,Female,No,Fair,Master,Good,No
...,...,...,...,...,...,...,...
995,S1995,Female,No,Fair,High School,Good,Yes
996,S1996,Female,Yes,Poor,High School,Average,Yes
997,S1997,Male,No,Good,Bachelor,Good,Yes
998,S1998,Male,Yes,Fair,Bachelor,Average,No
999,S1999,Female,No,Good,Bachelor,Average,No

In [7]:
x = numdata.drop('exam_score',axis=1)
y = numdata['exam_score']
x.head()

,age,study_hours_per_day,social_media_hours,netflix_hours,attendance_percentage,sleep_hours,exercise_frequency,mental_health_rating
0,23,0.0,1.2,1.1,85.0,8.0,6,8
1,20,6.9,2.8,2.3,97.3,4.6,6,8
2,21,1.4,3.1,1.3,94.8,8.0,1,1
3,23,1.0,3.9,1.0,71.0,9.2,4,1
4,19,5.0,4.4,0.5,90.9,4.9,3,1

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x,y,test_size=0.30,random_state=42)
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("Y_train:", Y_train.shape)
print("Y_test:", Y_test.shape)

X_train: (700, 8)
X_test: (300, 8)
Y_train: (700,)
Y_test: (300,)

In [9]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train,Y_train)

LinearRegression()

In [10]:
lr.score(X_train,Y_train)

0.9010117069230436

In [11]:
Y_train_pred = lr.predict(X_train)
Y_test_pred = lr.predict(X_test)

In [12]:
res = pd.DataFrame(
   { 
    "Actual" : Y_test.values,
    "Predicted" : Y_test_pred
    }
)

In [13]:
res

     Actual  Predicted
0      64.2  66.438797
1      72.7  74.824270
2      79.0  78.422311
3      79.5  74.603377
4      58.2  61.524044
..      ...        ...
295    66.8  65.354402
296    62.0  59.474289
297    52.4  53.028067
298    72.6  77.065112
299    57.3  55.588303

[300 rows x 2 columns]

In [14]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
tmean = mean_absolute_error(Y_train, Y_train_pred)
tmse = mean_squared_error(Y_train, Y_train_pred)
trmse = tmse ** 0.5  
tr2 = r2_score(Y_train, Y_train_pred)
print("Ttraing Data Set ")
print("Mean Absi=olute Error :", tmean)
print("Mean Squatrd Error :", tmse)
print("TRMSE:", trmse)
print("R2  :", tr2)

Ttraing Data Set
Mean Absi=olute Error : 4.219233116263186
Mean Squatrd Error : 28.48452021343859
TRMSE: 5.33708911424932
R2  : 0.9010117069230436

In [20]:
tmae = mean_absolute_error(Y_test, Y_test_pred)
tmse = mean_squared_error(Y_test, Y_test_pred)
trmse = tmse ** 0.5
tr2 = r2_score(Y_test, Y_test_pred)

print("Test Data Set ")
print("Mean Absi=olute Error :", tmean)
print("Mean Squatrd Error :", tmse)
print("TRMSE:", trmse)
print("R2  :", tr2)

Test Data Set
Mean Absi=olute Error : 4.219233116263186
Mean Squatrd Error : 28.233184730941794
TRMSE: 5.313490823455123
R2  : 0.8983545515482991

In [16]:
lr.coef_

array([ 0.06960354,  9.59188927, -2.74450869, -2.37359222,  0.1459774 ,
        2.02307756,  1.27787585,  1.94070414])

In [17]:
lr.intercept_

5.675772892516207

### Done Prediction OF Student Habitis Performance